(() => {
  'use strict';
  const KEY='vtrade-new-settings-v1';
  const API='https://forexai-6xw6.onrender.com';
  const SCORE_TIERS=[10,15,25,35,45,55,65,75,85,95,100];
  const defaults={autoTrade:false,autoLot:true,risk:1,fixedLot:0.01,maxLot:0.02,maxTrades:1,dailyLoss:5,killSwitch:false,symbols:{XAUUSD:true,GBPUSD:false,EURUSD:false,USDJPY:false,NAS100:false,US30:false}};
  const load=()=>{try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');return {...defaults,...x,symbols:{...defaults.symbols,...(x.symbols||{})}}}catch{return {...defaults,symbols:{...defaults.symbols}}}};
  const state=load(); const save=()=>localStorage.setItem(KEY,JSON.stringify(state)); const $=s=>document.querySelector(s),content=$('#main'),app=$('#app'),shade=$('#drawerShade');
  let livePrice=null,liveReady=false;
  let signal={signal:'WAIT',score:0,bias:'NEUTRAL',authorized:false,entry:null,sl:null,tp:[null,null,null],timeframe:'M15',closedCandle:false,rsSpProtected:false,reason:'Waiting for validated market snapshot'};
  const num=(...v)=>{for(const x of v){const n=Number(x);if(Number.isFinite(n)&&n>0)return n}return null};
  const clampScore=v=>{const n=Math.max(-100,Math.min(100,Number(v)||0));return n===0?0:SCORE_TIERS.reduce((a,b)=>Math.abs(b-Math.abs(n))<Math.abs(a-Math.abs(n))?b:a)*(n<0?-1:1)};
  async function refresh(){const conn=document.querySelector('.conn,.live-chip');try{const r=await fetch(`${API}/api/pre-market/mt5-authoritative`,{credentials:'omit',cache:'no-store'});const d=await r.json().catch(()=>({}));const p=num(d?.price,d?.livePrice,d?.currentPrice,d?.quote?.price,d?.quote?.bid,d?.quote?.ask,d?.mt5?.price,d?.data?.price,d?.data?.livePrice);if(!r.ok||p===null)throw Error('MT5 price unavailable');livePrice=p;liveReady=true;if(conn){conn.classList.add('ready');conn.title='MT5 live price connected'}document.querySelectorAll('[data-live-price]').forEach(n=>n.textContent=p.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}));document.querySelectorAll('[data-live-feed]').forEach(n=>n.textContent='MT5 LIVE · XAUUSD');document.querySelectorAll('[data-mt5-state]').forEach(n=>n.textContent='CONNECTED');}catch(e){liveReady=false;if(conn){conn.classList.remove('ready');conn.title='MT5 live price unavailable'}document.querySelectorAll('[data-live-feed]').forEach(n=>n.textContent='MT5 FEED WAITING');document.querySelectorAll('[data-mt5-state]').forEach(n=>n.textContent='WAITING');}}
  async function refreshSignal(){try{const r=await fetch(`${API}/api/telegram/market-snapshot`,{credentials:'omit',cache:'no-store'});const d=await r.json().catch(()=>({}));const s=d?.signal||d?.analysis||d?.data||d;if(s&&typeof s==='object'){const raw=String(s.signal||s.action||'WAIT').toUpperCase();const score=clampScore(s.score);const direction=score>0?'BUY':score<0?'SELL':'WAIT';const safeSignal=raw.includes('BUY')||raw.includes('BULL')?'BUY':raw.includes('SELL')||raw.includes('BEAR')?'SELL':direction;signal={...signal,signal:safeSignal==='BUY'?'BUY / BULLISH':safeSignal==='SELL'?'SELL / BEARISH':'WAIT',score,bias:safeSignal==='BUY'?'BULLISH':safeSignal==='SELL'?'BEARISH':(s.bias||s.direction||'NEUTRAL'),authorized:s.authorized===true,entry:num(s.entry,s.entryPrice)||signal.entry,sl:num(s.sl,s.stopLoss)||signal.sl,tp:Array.isArray(s.tp)?s.tp.slice(0,3):signal.tp,timeframe:s.timeframe||signal.timeframe,closedCandle:s.closedCandle===true||s.candleClosed===true,rsSpProtected:s.rsSpProtected===true||s.rs_sp_protected===true,reason:s.reason||s.reasons||signal.reason}}}catch(e){signal={...signal,authorized:false,reason:'Signal API unavailable — fail closed'}}renderSignal();}
  function fmt(v){return v==null?'—':Number(v).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}
  function renderSignal(){document.querySelectorAll('[data-signal]').forEach(n=>n.textContent=signal.signal||'WAIT');document.querySelectorAll('[data-score]').forEach(n=>n.textContent=(signal.score>0?'+':'')+signal.score);document.querySelectorAll('[data-bias]').forEach(n=>n.textContent=signal.bias||'NEUTRAL');document.querySelectorAll('[data-entry]').forEach(n=>n.textContent=fmt(signal.entry));document.querySelectorAll('[data-sl]').forEach(n=>n.textContent=fmt(signal.sl));['0','1','2'].forEach(i=>document.querySelectorAll(`[data-tp="${i}"]`).forEach(n=>n.textContent=fmt(signal.tp?.[Number(i)])));const a=document.querySelector('[data-authority]');if(a)a.textContent=signal.authorized?'READY':'WAIT';document.querySelectorAll('[data-candle]').forEach(n=>n.textContent=signal.closedCandle?'CLOSED':'WAIT');document.querySelectorAll('[data-rssp]').forEach(n=>n.textContent=signal.rsSpProtected?'PROTECTED':'WAIT');}
  const card=(title,value,sub='')=>`<div class="card"><div class="muted">${title}</div><h2>${value}</h2>${sub?`<small>${sub}</small>`:''}</div>`;
  const tierBar=()=>SCORE_TIERS.map(v=>`<span class="tab ${Math.abs(signal.score)===v?'active':''}">${signal.score<0?'-':''}${v}</span>`).join('');
  const pages={
    dashboard:()=>`<div class="hero"><div><div class="muted">LIVE MARKET</div><div class="title">XAUUSD</div></div><div class="price" data-live-price>${fmt(livePrice)}</div></div><div class="grid">${card('MT5 CONNECTION',liveReady?'CONNECTED':'CONNECTING',liveReady?'MT5 LIVE · XAUUSD':'Waiting for live feed')}${card('BIAS',signal.bias,'MTF ICT + CRT')}${card('SIGNAL',signal.signal,`Score <b data-score>${signal.score}</b> · Authority <b data-authority>${signal.authorized?'READY':'WAIT'}</b>`)}</div><div class="section card"><div class="row"><b>Realtime Setup</b><span class="muted">${signal.timeframe}</span></div><div class="status" style="margin-top:10px"><b>Entry</b> <span data-entry>${fmt(signal.entry)}</span> · <b>SL</b> <span data-sl>${fmt(signal.sl)}</span> · <b>TP1</b> <span data-tp="0">${fmt(signal.tp?.[0])}</span> · <b>TP2</b> <span data-tp="1">${fmt(signal.tp?.[1])}</span> · <b>TP3</b> <span data-tp="2">${fmt(signal.tp?.[2])}</span></div></div><div class="section card"><div class="row"><b>ICT Flow</b><button class="btn" id="toggleIct">Show</button></div><div id="ictDetails" hidden><div class="status" style="margin-top:10px">Liquidity → MSS/BOS → FVG/OB → CRT → RS/SP → Execution Guard</div></div></div>`,
    signals:()=>`<div class="hero"><div><div class="muted">AI SIGNAL ENGINE</div><div class="title">XAUUSD · REALTIME</div></div><span class="live-chip">REALTIME</span></div><div class="card"><div class="row"><div><div class="muted">CURRENT SIGNAL</div><h1 data-signal>${signal.signal}</h1><div class="green" data-bias>${signal.bias}</div></div><div style="text-align:right"><div class="muted">SCORE</div><div class="price" data-score>${signal.score}</div><small>/ 100</small></div></div><div class="tabs" style="margin-top:14px">${tierBar()}</div></div><div class="grid" style="margin-top:12px">${card('AUTHORITY',signal.authorized?'READY':'WAIT','All execution gates required')}${card('CANDLE',signal.closedCandle?'CLOSED':'WAIT','Fake candle rejected')}${card('RS/SP',signal.rsSpProtected?'PROTECTED':'WAIT','Liquidity SL protection')}${card('MT5',liveReady?'CONNECTED':'WAITING','Realtime XAUUSD')}</div><div class="section card"><div class="row"><b>Trade Setup</b><span class="muted">${signal.timeframe}</span></div><div class="status" style="margin-top:10px">Entry <b data-entry>${fmt(signal.entry)}</b> · SL <b data-sl>${fmt(signal.sl)}</b> · TP1 <b data-tp="0">${fmt(signal.tp?.[0])}</b> · TP2 <b data-tp="1">${fmt(signal.tp?.[1])}</b> · TP3 <b data-tp="2">${fmt(signal.tp?.[2])}</b></div><div class="status" style="margin-top:10px">Candle: <b data-candle>${signal.closedCandle?'CLOSED':'WAIT'}</b> · RS/SP: <b data-rssp>${signal.rsSpProtected?'PROTECTED':'WAIT'}</b> · ${signal.reason}</div></div>`,
    ict:()=>`<div class="hero"><div><div class="muted">SMART MONEY ANALYSIS</div><div class="title">ICT + CRT</div></div><span class="live-chip">${liveReady?'LIVE':'WAIT'}</span></div><div class="grid">${card('ICT','CONFIRMED','Liquidity + Structure')}${card('CRT','CONFIRMED','Confluence')}${card('LIQUIDITY','GUARDED','Sweep / protection')}</div><div class="section card"><div class="row"><b>Execution Sequence</b><button class="btn" id="toggleIct">Show</button></div><div id="ictDetails" hidden><div class="status" style="margin-top:10px">Liquidity Sweep → MSS/BOS → FVG/OB → CRT → RS/SP → Entry → SL → TP1/TP2/TP3</div></div></div>`,
    mtf:()=>`<div class="hero"><div><div class="muted">MULTI-TIMEFRAME SCANNER</div><div class="title">XAUUSD MTF</div></div><span class="live-chip" data-live-feed>${liveReady?'MT5 LIVE':'MT5 FEED WAITING'}</span></div><div class="grid">${['M5','M15','H1','H4','D1'].map((tf,i)=>`<div class="card"><div class="muted">${tf}</div><h2>${i<3?(signal.bias||'NEUTRAL'):'WAIT'}</h2><small>Score ${i<3?(signal.score||0):'—'}</small></div>`).join('')}</div><div class="section card"><div class="row"><b>MTF Rule</b><span class="green">CLOSED CANDLE</span></div><div class="status" style="margin-top:10px">No fake candle. No incomplete timeframe. Signal waits for valid MT5 OHLC and cross-timeframe confirmation.</div></div>`,
    terminal:()=>`<div class="hero"><div><div class="muted">MT5 TERMINAL</div><div class="title">Auto Trade Control</div></div><button class="btn ${state.killSwitch?'danger':''}" id="kill">${state.killSwitch?'KILL SWITCH ON':'KILL SWITCH'}</button></div><div class="card"><div class="row"><div><b>Auto Trade</b><div class="muted">Allow validated signals to reach MT5</div></div><button class="switch ${state.autoTrade&&!state.killSwitch?'on':''}" id="auto" aria-label="Auto Trade"><i></i></button></div></div><div class="section card"><div class="row"><b>Execution Guard</b><button class="btn" id="toggleGuard">Show</button></div><div id="guardDetails" hidden><div class="status" style="margin-top:10px">Closed candle · Fake candle guard · MT5 freshness · RS/SP liquidity protection · SL/TP validation · duplicate-order protection.</div></div></div>`,
    trades:()=>`<div class="title">Trade History</div><div class="section card"><table class="table"><thead><tr><th>Symbol</th><th>Side</th><th>Lot</th><th>Status</th></tr></thead><tbody><tr><td>XAUUSD</td><td>—</td><td>—</td><td class="muted">No live order</td></tr></tbody></table></div>`,
    settings:()=>`<div class="title">Settings</div><div class="section card"><div class="row"><b>Backend</b><span class="green">LIVE</span></div><div class="row" style="margin-top:14px"><b>MT5 Execution</b><span class="muted">Demo-first</span></div><div class="row" style="margin-top:14px"><b>Telegram</b><span class="green">V-Zone AI</span></div><div class="status" style="margin-top:14px">Advanced controls stay hidden by default.</div></div>`
  };
  function closeDrawer(){app.classList.remove('drawer-open');shade.classList.remove('show')}
  function openDrawer(){app.classList.add('drawer-open');shade.classList.add('show')}
  function render(page='dashboard'){const target=pages[page]?page:'dashboard';content.innerHTML=pages[target]();document.querySelectorAll('.nav').forEach(b=>{const active=b.dataset.page===target;b.classList.toggle('active',active);b.toggleAttribute('aria-current',active);});bind(target);closeDrawer();refresh();refreshSignal();content.focus?.()}
  function bind(page){$('#toggleIct')?.addEventListener('click',()=>{const d=$('#ictDetails'),hide=d.hidden;d.hidden=!hide;$('#toggleIct').textContent=hide?'Hide':'Show'});$('#toggleGuard')?.addEventListener('click',()=>{const d=$('#guardDetails'),hide=d.hidden;d.hidden=!hide;$('#toggleGuard').textContent=hide?'Hide':'Show'});if(page==='terminal'){$('#auto')?.addEventListener('click',()=>{if(state.killSwitch)return;state.autoTrade=!state.autoTrade;save();render('terminal')});$('#kill')?.addEventListener('click',()=>{state.killSwitch=!state.killSwitch;if(state.killSwitch)state.autoTrade=false;save();render('terminal')})}}
  document.querySelectorAll('.nav').forEach(b=>b.addEventListener('click',()=>render(b.dataset.page)));
  $('#menu')?.addEventListener('click',()=>app.classList.contains('drawer-open')?closeDrawer():openDrawer());
  shade?.addEventListener('click',closeDrawer);
  $('#themeBtn')?.addEventListener('click',()=>document.documentElement.classList.toggle('light'));
  render('dashboard');setInterval(refresh,5000);setInterval(refreshSignal,5000);
})();
