(() => {
  'use strict';
  const KEY='vtrade-new-settings-v1';
  const API='https://forexai-6xw6.onrender.com';
  const defaults={autoTrade:false,autoLot:true,risk:1,fixedLot:0.01,maxLot:0.02,maxTrades:1,dailyLoss:5,killSwitch:false,symbols:{XAUUSD:true,GBPUSD:false,EURUSD:false,USDJPY:false,NAS100:false,US30:false}};
  const load=()=>{try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');return {...defaults,...x,symbols:{...defaults.symbols,...(x.symbols||{})}}}catch{return structuredClone(defaults)}};
  const state=load(); const save=()=>localStorage.setItem(KEY,JSON.stringify(state)); const $=s=>document.querySelector(s); const content=$('#main'),app=$('#app'),shade=$('#drawerShade');
  let livePrice=null,liveReady=false,signal={signal:'WAIT',score:0,bias:'NEUTRAL',authorized:false,entry:null,sl:null,tp:[null,null,null],timeframe:'M15'};
  const num=(...v)=>{for(const x of v){const n=Number(x);if(Number.isFinite(n)&&n>0)return n}return null};
  async function refresh(){const conn=document.querySelector('.conn');try{const r=await fetch(`${API}/api/pre-market/mt5-authoritative`,{credentials:'omit',cache:'no-store'});const d=await r.json().catch(()=>({}));const p=num(d?.price,d?.livePrice,d?.currentPrice,d?.quote?.price,d?.quote?.bid,d?.quote?.ask,d?.mt5?.price,d?.data?.price,d?.data?.livePrice);if(!r.ok||p===null)throw Error('MT5 price unavailable');livePrice=p;liveReady=true;if(conn){conn.classList.add('ready');conn.title='MT5 live price connected'}document.querySelectorAll('[data-live-price]').forEach(n=>n.textContent=p.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}));const f=document.querySelector('[data-live-feed]');if(f)f.textContent='MT5 LIVE · XAUUSD';}catch(e){liveReady=false;if(conn){conn.classList.remove('ready');conn.title='MT5 live price unavailable'}const f=document.querySelector('[data-live-feed]');if(f)f.textContent='MT5 FEED WAITING';}}
  async function refreshSignal(){try{const r=await fetch(`${API}/api/telegram/market-snapshot`,{credentials:'omit',cache:'no-store'});const d=await r.json().catch(()=>({}));const s=d?.signal||d?.analysis||d?.data||d;if(s&&typeof s==='object'){signal={...signal,signal:s.signal||s.action||signal.signal,score:Number(s.score)||0,bias:s.bias||s.direction||signal.bias,authorized:s.authorized===true,entry:num(s.entry,s.entryPrice)||signal.entry,sl:num(s.sl,s.stopLoss)||signal.sl,tp:Array.isArray(s.tp)?s.tp.slice(0,3):signal.tp,timeframe:s.timeframe||signal.timeframe}}}catch(e){signal={...signal,authorized:false}}renderSignal();}
  function fmt(v){return v==null?'—':Number(v).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}
  function renderSignal(){document.querySelectorAll('[data-signal]').forEach(n=>n.textContent=signal.signal||'WAIT');document.querySelectorAll('[data-score]').forEach(n=>n.textContent=(signal.score>0?'+':'')+signal.score);document.querySelectorAll('[data-bias]').forEach(n=>n.textContent=signal.bias||'NEUTRAL');document.querySelectorAll('[data-entry]').forEach(n=>n.textContent=fmt(signal.entry));document.querySelectorAll('[data-sl]').forEach(n=>n.textContent=fmt(signal.sl));['0','1','2'].forEach((i)=>document.querySelectorAll(`[data-tp="${i}"]`).forEach(n=>n.textContent=fmt(signal.tp?.[Number(i)])));const a=document.querySelector('[data-authority]');if(a)a.textContent=signal.authorized?'READY':'WAIT';}
  const pages={
    dashboard:()=>`<div class="hero"><div><div class="muted">LIVE MARKET</div><div class="title">XAUUSD</div></div><div class="price" data-live-price>${fmt(livePrice)}</div></div><div class="grid"><div class="card"><div class="muted">MT5 CONNECTION</div><h2 class="green">${liveReady?'CONNECTED':'CONNECTING'}</h2><small data-live-feed>${liveReady?'MT5 LIVE · XAUUSD':'Waiting for live feed'}</small></div><div class="card"><div class="muted">BIAS</div><h2 data-bias>${signal.bias}</h2><small>MTF ICT + CRT</small></div><div class="card"><div class="muted">SIGNAL</div><h2 data-signal>${signal.signal}</h2><small>Score <b data-score>${signal.score}</b> · Authority <b data-authority>${signal.authorized?'READY':'WAIT'}</b></small></div></div><div class="section card"><div class="row"><b>Realtime Setup</b><span class="muted">${signal.timeframe}</span></div><div class="status" style="margin-top:10px"><b>Entry</b> <span data-entry>${fmt(signal.entry)}</span> · <b>SL</b> <span data-sl>${fmt(signal.sl)}</span> · <b>TP1</b> <span data-tp="0">${fmt(signal.tp?.[0])}</span> · <b>TP2</b> <span data-tp="1">${fmt(signal.tp?.[1])}</span> · <b>TP3</b> <span data-tp="2">${fmt(signal.tp?.[2])}</span></div></div><div class="section card"><div class="row"><b>ICT Flow</b><button class="btn" id="toggleIct">Show</button></div><div id="ictDetails" hidden><div class="status" style="margin-top:10px">Liquidity → MSS/BOS → FVG/OB → CRT → RS/SP → Execution Guard</div></div></div>`,
    terminal:()=>`<div class="hero"><div><div class="muted">MT5 TERMINAL</div><div class="title">Auto Trade Control</div></div><button class="btn ${state.killSwitch?'danger':''}" id="kill">${state.killSwitch?'KILL SWITCH ON':'KILL SWITCH'}</button></div><div class="card"><div class="row"><div><b>Auto Trade</b><div class="muted">Allow validated signals to reach MT5</div></div><button class="switch ${state.autoTrade&&!state.killSwitch?'on':''}" id="auto" aria-label="Auto Trade"><i></i></button></div></div><div class="section card"><div class="row"><b>Execution Guard</b><button class="btn" id="toggleGuard">Show</button></div><div id="guardDetails" hidden><div class="status" style="margin-top:10px">Closed candle · Fake candle guard · MT5 freshness · RS/SP liquidity protection · SL/TP validation · duplicate-order protection.</div></div></div>`,
    signals:()=>`<div class="title">Signals</div><div class="section grid"><div class="card"><div class="muted">XAUUSD · REALTIME</div><h2 data-signal>${signal.signal}</h2><div>Score <b data-score>${signal.score}</b> · <span data-bias>${signal.bias}</span></div></div><div class="card"><div class="muted">AUTHORITY</div><h2 data-authority>${signal.authorized?'READY':'WAIT'}</h2><div class="muted">No order unless all gates pass</div></div></div>`,
    trades:()=>`<div class="title">Trade History</div><div class="section card"><table class="table"><thead><tr><th>Symbol</th><th>Side</th><th>Lot</th><th>Status</th></tr></thead><tbody><tr><td>XAUUSD</td><td>—</td><td>—</td><td class="muted">No live order</td></tr></tbody></table></div>`,
    settings:()=>`<div class="title">Settings</div><div class="section card"><div class="row"><b>Backend</b><span class="green">LIVE</span></div><div class="row" style="margin-top:14px"><b>MT5 Execution</b><span class="muted">Demo-first</span></div><div class="row" style="margin-top:14px"><b>Telegram</b><span class="green">V-Zone AI</span></div><div class="status" style="margin-top:14px">Advanced controls stay hidden by default.</div></div>`
  };
  function closeDrawer(){app.classList.remove('drawer-open');shade.classList.remove('show')} function openDrawer(){app.classList.add('drawer-open');shade.classList.add('show')}
  function render(page='dashboard'){content.innerHTML=pages[page]?pages[page]():pages.dashboard();document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.page===page));bind(page);closeDrawer();refresh();refreshSignal();}
  function bind(page){$('#toggleIct')?.addEventListener('click',()=>{const d=$('#ictDetails'),hide=d.hidden;d.hidden=!hide;$('#toggleIct').textContent=hide?'Hide':'Show'});$('#toggleGuard')?.addEventListener('click',()=>{const d=$('#guardDetails'),hide=d.hidden;d.hidden=!hide;$('#toggleGuard').textContent=hide?'Hide':'Show'});if(page==='terminal'){$('#auto')?.addEventListener('click',()=>{if(state.killSwitch)return;state.autoTrade=!state.autoTrade;save();render('terminal')});$('#kill')?.addEventListener('click',()=>{state.killSwitch=!state.killSwitch;if(state.killSwitch)state.autoTrade=false;save();render('terminal')})}}
  document.querySelectorAll('.nav').forEach(b=>b.addEventListener('click',()=>render(b.dataset.page)));$('#menu').addEventListener('click',()=>app.classList.contains('drawer-open')?closeDrawer():openDrawer());shade.addEventListener('click',closeDrawer);render('dashboard');setInterval(refresh,5000);setInterval(refreshSignal,5000);
})();
